# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c71cf78b8ecf19b6a9ab9b4efc1009de04f9a831988111ab1710c633503710ed22bee302ecfab7e03c1067f13fdf9cf500a6a10dfe6089d94211ac7e48659249
  twilio_account_sid: AC6d7cbd146b8c78fc99d8cb680c9d7fb7
  twilio_auth_token: fde2a5358e7e401c7bd66feb52b45604

test:
  secret_key_base: 2a01bcf53f4192e156a9c755d7d256ae31b80c7c216e7fce985ffc2482ff94f2d119c25b125c3347f9cfcb80f160e82e808a883f5c0471cb8f7f4c515331bfe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c71cf78b8ecf19b6a9ab9b4efc1009de04f9a831988111ab1710c633503710ed22bee302ecfab7e03c1067f13fdf9cf500a6a10dfe6089d94211ac7e48659249
  twilio_account_sid: AC6d7cbd146b8c78fc99d8cb680c9d7fb7
  twilio_auth_token: fde2a5358e7e401c7bd66feb52b45604
